version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: django101
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 5dc2e8facd34375310256cf9f6721e8d

  web:
    build: .
    image: django101
    command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      NAME: django101  #Nombre base de datos
      USER: test #Usuario Base de dato
      PASSWORD: 5dc2e8facd34375310256cf9f6721e8d #Contraseña Base de datos
      HOST: db #Contenedor base de datos

